version: '3.8'

services:
  flow2api-headed:
    init: true
    build:
      context: .
      dockerfile: Dockerfile.headed
    image: flow2api:headed
    container_name: flow2api-headed
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./tmp:/app/tmp
      - ./config/setting.toml:/app/config/setting.toml
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOW_DOCKER_HEADED_CAPTCHA=true
      - DISPLAY=:99
      - XVFB_SCREEN=1440x900x24
    shm_size: "2gb"
    restart: unless-stopped
